import logging
import os
from logging.config import fileConfig

from collections.abc import Iterable, MutableMapping
from typing import Literal

from alembic import context
from alembic.operations.ops import MigrationScript
from alembic.runtime.migration import MigrationContext
from app.config import settings
from app.database import Base
from app.models.base import Chunk, Document  # noqa
from app.models.message import Message  # noqa
from app.models.user import User  # noqa
from sqlalchemy import Column, engine_from_config, pool, text
from sqlalchemy.schema import SchemaItem
from sqlalchemy.types import TypeEngine

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

logger = logging.getLogger("alembic.env")

# add your model's MetaData object here
# for 'autogenerate' support
target_metadata = Base.metadata

# ---------------------------------------------------------------------------
# Schema reflection contract
# ---------------------------------------------------------------------------
# All app tables live in the "quaero" schema.  The application DATABASE_URL
# sets search_path=quaero, making default_schema_name="quaero".  Alembic
# replaces the default schema with None internally, so reflected quaero
# tables arrive as schema=None while our models declare schema='quaero'
# explicitly.  This mismatch causes false-positive diffs:
#
#   1. FK churn — remove FK(users.id) + add FK(quaero.users.id) on every
#      table with foreign keys, even though nothing changed on disk.
#   2. ENUM type diffs — reflected PG ENUMs have schema='quaero' but model
#      Enums have no schema qualifier.
#   3. DROP TABLE alembic_version — reflected as schema=None, not in any
#      model, so autogenerate proposes removing it.
#
# Fix: the migration engine overrides search_path to "public" so that
# default_schema_name="public" and quaero tables are reflected with their
# explicit schema='quaero', matching model metadata exactly.  Combined with:
#   a) include_name — only reflect the quaero schema.
#   b) include_object — reject non-quaero objects and infrastructure tables.
#   c) compare_type — suppress schema-qualified ENUM false positives.
#   d) process_revision_directives — block dangerous autogenerated ops.
# ---------------------------------------------------------------------------

APP_SCHEMA = target_metadata.schema  # "quaero"

# Names of tables managed by Alembic/infrastructure, not app models.
_INFRASTRUCTURE_TABLES = frozenset({"alembic_version"})


def include_name(
    name: str | None,
    type_: Literal["schema", "table", "column", "index", "unique_constraint", "foreign_key_constraint"],
    parent_names: MutableMapping[
        Literal["schema_name", "table_name", "schema_qualified_table_name"],
        str | None,
    ],
) -> bool:
    """Control which schema names Alembic reflects during autogenerate.

    Only allow APP_SCHEMA so that public-schema objects (extension tables,
    other apps' tables) are never loaded into the reflected metadata.
    With search_path=public on the migration connection, the default schema
    is "public" (passed as None), so blocking None filters out public objects.
    """
    if type_ == "schema":
        return name == APP_SCHEMA
    return True


def compare_type(
    context: MigrationContext,
    inspected_column: Column[object],
    metadata_column: Column[object],
    inspected_type: TypeEngine[object],
    metadata_type: TypeEngine[object],
) -> bool | None:
    """Suppress false-positive type diffs caused by schema qualification.

    When search_path=public, PostgreSQL reflects ENUMs with schema='quaero'
    but the model Enum has no schema.  The underlying type is identical;
    only the schema qualifier differs.  Return False to suppress the diff.
    """
    from sqlalchemy import Enum as SAEnum
    from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM

    if isinstance(inspected_type, PG_ENUM) and isinstance(metadata_type, SAEnum):
        # Compare by enum name and values, ignoring schema qualifier.
        if (
            getattr(inspected_type, "name", None) == getattr(metadata_type, "name", None)
            and getattr(inspected_type, "enums", None) == getattr(metadata_type, "enums", None)
        ):
            return False

    # Return None to let Alembic's default comparison handle it.
    return None


def include_object(
    object: SchemaItem,
    name: str | None,
    type_: Literal["schema", "table", "column", "index", "unique_constraint", "foreign_key_constraint"],
    reflected: bool,
    compare_to: SchemaItem | None,
) -> bool:
    """Restrict autogenerate to APP_SCHEMA objects only.

    Rejects:
    - Tables/objects with an explicit schema that isn't APP_SCHEMA
    - Infrastructure tables (alembic_version) that are not app models
    """
    # Reject objects from non-app explicit schemas.
    schema = getattr(object, "schema", None)
    if schema is not None and schema != APP_SCHEMA:
        return False

    # Reject infrastructure tables that aren't app models.
    if type_ == "table" and reflected and name in _INFRASTRUCTURE_TABLES:
        return False

    return True


# ---------------------------------------------------------------------------
# Autogenerate guardrails (process_revision_directives)
# ---------------------------------------------------------------------------
# These guardrails run after autogenerate computes a diff but before the
# migration script is written.  They reject dangerous or noisy operations
# that should never appear in a committed migration without explicit review.
#
# Set ALEMBIC_UNSAFE_AUTOGEN=1 to bypass guardrails for intentional schema
# changes that would normally be blocked.
# ---------------------------------------------------------------------------

UNSAFE_AUTOGEN = os.environ.get("ALEMBIC_UNSAFE_AUTOGEN", "") == "1"


def _is_fk_schema_churn(op: object) -> bool:
    """Detect FK add/remove ops caused by schema qualification mismatch.

    When search_path=quaero, reflected FKs reference 'users.id' (unqualified)
    while model FKs reference 'quaero.users.id' (qualified).  Autogenerate
    emits remove_fk + add_fk pairs that change nothing on disk.
    """
    from alembic.operations.ops import AddConstraintOp, DropConstraintOp

    if not isinstance(op, (AddConstraintOp, DropConstraintOp)):
        return False

    constraint = getattr(op, "constraint", None)
    if constraint is None:
        return False

    from sqlalchemy import ForeignKeyConstraint

    return isinstance(constraint, ForeignKeyConstraint)


def process_revision_directives(
    context: MigrationContext,
    revision: str | Iterable[str | None] | Iterable[str],
    directives: list[MigrationScript],
) -> None:
    """Filter autogenerated migration ops to block dangerous/noisy changes."""
    if UNSAFE_AUTOGEN:
        logger.warning(
            "ALEMBIC_UNSAFE_AUTOGEN=1: skipping autogenerate guardrails"
        )
        return

    if not directives:
        return

    script = directives[0]
    if script.upgrade_ops is None:
        return

    ops = script.upgrade_ops.ops
    filtered: list[object] = []
    blocked: list[str] = []

    for op in ops:
        op_id = getattr(op, "op", type(op).__name__)

        # Block 1: DROP TABLE on non-app objects (e.g. alembic_version).
        if op_id == "drop_table":
            table_name = getattr(op, "table_name", "")
            schema = getattr(op, "schema", None)
            if schema is None or schema != APP_SCHEMA:
                blocked.append(
                    f"drop_table {schema or 'public'}.{table_name}"
                )
                continue

        # Block 2: Any op targeting an explicit schema other than APP_SCHEMA.
        op_schema = getattr(op, "schema", "MISSING")
        if op_schema != "MISSING" and op_schema is not None and op_schema != APP_SCHEMA:
            blocked.append(f"{op_id} on non-app schema {op_schema}")
            continue

        # Block 3: FK schema-qualification churn (remove+add pairs that
        # differ only in whether the referred table is schema-qualified).
        if _is_fk_schema_churn(op):
            constraint = getattr(op, "constraint", None)
            constraint_name = getattr(constraint, "name", None) or "unnamed"
            blocked.append(f"FK churn: {op_id} {constraint_name}")
            continue

        filtered.append(op)

    if blocked:
        logger.info(
            "Autogenerate guardrails blocked %d operation(s):\n  %s",
            len(blocked),
            "\n  ".join(blocked),
        )

    script.upgrade_ops.ops = filtered  # type: ignore[assignment]


# ---------------------------------------------------------------------------
# Migration runners
# ---------------------------------------------------------------------------

# Shared context.configure kwargs for both online and offline modes.
def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL and not an Engine, though an
    Engine is acceptable here as well.  By skipping the Engine creation we
    don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the script output.
    """
    context.configure(
        url=settings.database_url,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        target_metadata=target_metadata,
        version_table_schema=APP_SCHEMA,
        include_schemas=True,
        include_name=include_name,
        include_object=include_object,
        compare_type=compare_type,
        process_revision_directives=process_revision_directives,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode. Creates quaero schema if missing.

    The engine is created with search_path=public so that the dialect's
    default_schema_name is "public", not "quaero".  This is critical for
    autogenerate: with include_schemas=True, Alembic replaces the default
    schema with None internally.  If default_schema_name were "quaero",
    reflected tables would arrive as schema=None while our models declare
    schema='quaero', causing false-positive FK diffs.  With
    default_schema_name="public", quaero tables are reflected with their
    explicit schema='quaero', matching model metadata exactly.
    """
    configuration = config.get_section(config.config_ini_section, {})
    configuration["sqlalchemy.url"] = settings.database_url

    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
        # Force search_path=public so default_schema_name != APP_SCHEMA.
        # Without this, if DATABASE_URL sets search_path=quaero (as ours
        # does), reflected quaero tables get schema=None and autogenerate
        # sees phantom FK diffs.
        connect_args={"options": "-csearch_path=public"},
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            version_table_schema=APP_SCHEMA,
            include_schemas=True,
            include_name=include_name,
            include_object=include_object,
            compare_type=compare_type,
            process_revision_directives=process_revision_directives,
        )

        with context.begin_transaction():
            connection.execute(
                text(f"CREATE SCHEMA IF NOT EXISTS {APP_SCHEMA}")
            )
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
