"""Application wide constants."""

# FILE UPLOAD
MAX_FILE_SIZE_MB = 10
MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024
ALLOWED_EXTENSIONS = {".pdf"}
UPLOAD_CHUNK_SIZE_BYTES = 1024 * 1024

# TEXT CHUNKING
DEFAULT_CHUNK_SIZE = 500
DEFAULT_CHUNK_OVERLAP = 50
