"""Application wide constants."""

# FILE UPLOAD
MAX_FILE_SIZE_MB = 10
MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024
ALLOWED_EXTENSIONS = {".pdf"}
UPLOAD_CHUNK_SIZE_BYTES = 1024 * 1024
# PDF magic bytes per spec (files must start with %PDF-)
PDF_MAGIC_BYTES = b"%PDF-"

# TEXT CHUNKING
DEFAULT_CHUNK_SIZE = 1000
DEFAULT_CHUNK_OVERLAP = 50

# PDF PROCESSING
PDF_PROCESSING_TIMEOUT_SECONDS = 30

# OPENAI EMBEDDINGS
EMBEDDING_MODEL = "text-embedding-3-small"
EMBEDDING_DIMENSIONS = 1536
EMBEDDING_BATCH_SIZE = 100
